# Generated by Django 4.0.6 on 2022-07-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_alter_post_content_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('place', models.CharField(max_length=20)),
                ('detail_content', models.TextField(max_length=200)),
            ],
        ),
    ]
