# Generated by Django 4.0.6 on 2022-07-11 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0004_schedule_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='post',
            field=models.ForeignKey(db_column='post_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='project_app.post'),
        ),
    ]
