# Generated by Django 4.0.6 on 2022-07-11 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_alter_schedule_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_app.post'),
        ),
    ]
