# Generated by Django 4.0.4 on 2022-07-08 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_remove_comment_post_comment_post_k'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_k',
            new_name='post',
        ),
    ]
