# Generated by Django 4.0.6 on 2022-07-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_alter_schedule_post'),
        ('project_app', '0006_rename_post_k_comment_post'),
    ]

    operations = [
    ]
