# Generated by Django 4.0.6 on 2022-07-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_remove_category_post_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
