# Generated by Django 4.0.6 on 2022-07-13 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_category_slug_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
