# Generated by Django 4.0.6 on 2022-07-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='detail_content',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='place',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
