# Generated by Django 4.0.6 on 2022-11-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0014_company_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
