# Generated by Django 4.0.6 on 2022-11-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0016_schedule_delete_company_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
