# Generated by Django 4.0.6 on 2022-11-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0017_delete_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
